// /*
// Auto-generated by: https://github.com/pmndrs/gltfjsx
// */

// import React, { useRef } from 'react'
// import { useGLTF } from '@react-three/drei'

// export function Mars(props) {
//   const { nodes, materials } = useGLTF('/mars_one_mission_-_base.glb')
//   return (
//     <group {...props} dispose={null}>
//       <group rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_10.geometry}
//           material={materials.material_8}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_11.geometry}
//           material={materials.material_9}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_12.geometry}
//           material={materials.material_10}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_14.geometry}
//           material={materials.material_12}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_14001.geometry}
//           material={materials.material_12}
//           position={[779.007, 0, 2.201]}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_15.geometry}
//           material={materials.material_13}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_16.geometry}
//           material={materials.material_14}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_17.geometry}
//           material={materials.material_15}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_18.geometry}
//           material={materials.material_16}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_19.geometry}
//           material={materials.material_17}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_2.geometry}
//           material={materials.material}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_20.geometry}
//           material={materials.material_18}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_21.geometry}
//           material={materials.material_19}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_22.geometry}
//           material={materials.material_20}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_23.geometry}
//           material={materials.material_21}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_24.geometry}
//           material={materials.material_22}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_25.geometry}
//           material={materials.material_23}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_26.geometry}
//           material={materials.material_24}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_27.geometry}
//           material={materials.material_25}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_28.geometry}
//           material={materials.material_26}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_3.geometry}
//           material={materials.material_1}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_30.geometry}
//           material={materials.material_28}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_4.geometry}
//           material={materials.material_2}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_5.geometry}
//           material={materials.material_3}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_7.geometry}
//           material={materials.material_5}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_8.geometry}
//           material={materials.material_6}
//         />
//         <mesh
//           castShadow
//           receiveShadow
//           geometry={nodes.Object_9.geometry}
//           material={materials.material_7}
//         />
//       </group>
//     </group>
//   )
// }

// useGLTF.preload('/mars_one_mission_-_base.glb')




import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Mars(props) {
  const { nodes, materials } = useGLTF('/world.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane001.geometry}
        material={materials['Material.001']}
        position={[-5502.654, 322.796, -1562.466]}
        scale={[6607.605, 3617.846, 3476.825]}
      />
    </group>
  )
}

useGLTF.preload('/world.glb')

